name: link-test
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linktest
        uses: beucismis-archive/linktest@main
        with:
          file-paths: "README.md"
